apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orderflow
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "1" }
spec:
  project: default
  sources:
    - repoURL: https://github.com/Oheneali22/orderflow.git
      targetRevision: main
      path: charts/orderflow
      helm:
        valueFiles: [$values/environments/production/values.yaml]
    - repoURL: https://github.com/Oheneali22/orderflow.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: orderflow
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
    syncOptions: [CreateNamespace=true]
