apiVersion: v1
kind: ConfigMap
metadata:
  name: orderflow-config
  namespace: orderflow

data:
  LOG_LEVEL: "info"

  DB_HOST: "orderflow-dev-postgres.c2jmoyokm51r.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "orderflow"

  API_PORT: "3000"

  WORKER_HEALTH_PORT: "3001"
  WORKER_POLL_INTERVAL_MS: "1000"
  WORKER_PROCESSING_DELAY_MS: "1500"
  WORKER_CLAIM_TIMEOUT_MS: "60000"
