apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orderflow-github-deployer
  namespace: orderflow
rules:
  - apiGroups:
      - secrets-store.csi.x-k8s.io
    resources:
      - secretproviderclasses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orderflow-github-deployer
  namespace: orderflow
subjects:
  - kind: Group
    name: orderflow-deployers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: orderflow-github-deployer
  apiGroup: rbac.authorization.k8s.io
