apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: orderflow-rds
  namespace: orderflow

spec:
  provider: aws

  parameters:
    region: us-east-1
    usePodIdentity: "true"

    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:942909611186:secret:rds!db-9b92c7b0-a4aa-4ade-9b18-a1934e2e19ce-2hiFSl"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db-username
          - path: password
            objectAlias: db-password
