apiVersion: v1
kind: Service
metadata:
  name: orderflow-api
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.api.service.type }}

  selector:
    app: orderflow-api

  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.config.apiPort }}