FROM node:22.23.2-bookworm-slim AS node
FROM docker:28.5.2-cli AS docker-cli

FROM jenkins/inbound-agent@sha256:f049411749dda6fe6fb4693458f9da6fadc8dd54f9fd52afa687db28b14fe322

USER root

COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
    && ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker

USER jenkins
