global:
  imageRegistry: 942909611186.dkr.ecr.us-east-1.amazonaws.com
  imageTag: sha-ced1b5013246c2eb879f51d642cc463fff465eaf

web:
  image:
    digest: sha256:9ed0c90a6dbfa9d03877e2e1ed62ce0fa2cac203edc62c4080e38c3ab618b8d5
api:
  image:
    digest: sha256:33b24aa5137505e3602796cfeadd891451c0987cf621ceff0f1a296f7c7d4d03
worker:
  image:
    digest: sha256:921e1e83f7f94140af303e26165933dca601725d8dbfcf343c98a1bed6d2ec54

externalSecret:
  enabled: true
  region: us-east-1
  remoteKey: orderflow-production/database-url

ingress:
  enabled: true
  className: nginx
  host: orderflow.example.com

serviceMonitor:
  enabled: true

prometheusRule:
  enabled: true

grafanaDashboard:
  enabled: true
