{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-aws-secrets-manager
  labels: {{- include "orderflow.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.region }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-database
  labels: {{- include "orderflow.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Release.Name }}-aws-secrets-manager
    kind: SecretStore
  target:
    name: {{ .Values.database.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.database.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.database.secretKey }}
{{- end }}
