{{- if .Values.podDisruptionBudget.enabled }}
{{- $root := . -}}
{{- range $name := list "web" "api" "worker" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $root.Release.Name }}-{{ $name }}
  labels: {{- include "orderflow.labels" $root | nindent 4 }}
spec:
  minAvailable: {{ $root.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "orderflow.selectorLabels" $root | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
---
{{- end }}
{{- end }}
